#!/bin/bash
set -e

echo "Running pre-commit checks..."

# Format
echo "Formatting code..."
find src/ test/ -name "*.c" -o -name "*.h" | xargs clang-format -i

# Build
echo "Building project..."
make build

# Test
echo "Running tests..."
make test

# All steps passed ok!
echo "All steps passed ok! :)"
exit 0
