#!/bin/bash
set -eo pipefail

echo "Running pre-commit checks..."

echo "⚠ Formatting code..."
find src/ test/ -name "*.c" -o -name "*.h" | xargs clang-format -i
echo "✓ Format process"

echo "⚠ Building project..."
make build
echo "✓ Build process"

echo "⚠ Running tests..."
make test
echo "✓ Tests execution"

echo "✓ All steps passed ok! :)"
exit 0
